# Generated by Django 4.0.4 on 2022-05-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_club', models.CharField(max_length=100)),
                ('pays_club', models.CharField(max_length=100)),
                ('date_parution_club', models.DateField(blank=True, null=True)),
                ('nombre_LDC', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur_ajout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_joueur', models.CharField(max_length=100)),
                ('pays_joueur', models.CharField(max_length=100)),
                ('date_naissance_joueur', models.DateField(blank=True, null=True)),
                ('nombre_LDC', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_joueur', models.CharField(max_length=100)),
                ('pays_joueur', models.CharField(max_length=100)),
                ('date_naissance_joueur', models.DateField(blank=True, null=True)),
                ('nombre_LDC', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.club')),
            ],
        ),
    ]
